<?php
namespace MyFramework\Common;

require_once FRAMEWORK_DIR . DS . 'Common' . DS . 'Router.php';

/**
 * Test class for Router.
 * Generated by PHPUnit on 2012-05-02 at 13:14:53.
 */
class RouterTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @covers MyFramework\Common\Router::route
	 * @todo Implement testRoute().
	 */
	public function testRoute() {
		// arrange
		$Request = new Request(NULL, NULL, NULL);
		$Router  = new Router($Request);

		// act
		$Controller = $Router->route();

		// assert
		$this->assertInstanceOf(APP_NAME . '\Controller\Pages', $Controller, 'returned controller is instance of MyApp\Controller\Pages');
		$this->assertEquals('index run with id: ' . NULL, $Controller->indexRun, 'controller ran index method');
	}

}
